In [74]:
import pandas as pd
import numpy as np
import csv

raw_data = pd.read_csv("Data_Project_Data.csv")
df_all = pd.DataFrame(raw_data)

values = {'pitch_type': 'NR'}
df_all = df_all.fillna(value = values)

In [75]:
df_all

,pitch_id,pitcher_id,pitcher_side,pitch_type,pitch_initial_speed_a,break_x_a,break_z_a,pitch_initial_speed_b,spinrate_b,break_x_b,break_z_b
0,1,15865,R,Fastball,89.7,-1.23,10.06,90.7214,2302.52,4.29402,-12.2448
1,2,15865,R,Fastball,89.9,-1.81,12.27,90.8140,2262.55,3.74221,-12.3771
2,3,15865,R,Fastball,91.9,-1.84,10.62,92.6839,2211.62,4.06159,-16.3200
3,4,15865,R,Fastball,90.7,-5.82,6.26,91.5610,2269.47,10.23910,-20.5354
4,5,15865,R,Fastball,88.9,-0.69,10.04,90.0486,2229.72,2.44025,-12.6229
...,...,...,...,...,...,...,...,...,...,...,...
4995,496,495134,R,NR,NaN,NaN,NaN,85.8881,1844.23,13.57330,-45.2486
4996,497,495134,R,NR,NaN,NaN,NaN,78.8214,2106.01,8.31108,-56.0769
4997,498,495134,R,NR,NaN,NaN,NaN,79.0890,2009.52,8.05088,-56.4618
4998,499,495134,R,NR,NaN,NaN,NaN,84.8703,1838.71,15.25150,-46.2941
4999,500,495134,R,NR,NaN,NaN,NaN,84.3275,1853.77,14.99320,-47.9555

In [76]:
pitcher_id = df_all.pitcher_id.unique()
pitcher_id

array([ 15865,  16401,  34909,  58040,  66538,  96028, 104574, 466401,
       480028, 495134])

In [77]:
p_types = df_all.pitch_type.unique()
p_types

array(['Fastball', 'Slider', 'Curveball', 'Changeup', 'NR'], dtype=object)

In [78]:
column_names = list(df_all.columns)

In [79]:
df_nonclassified = df_all.loc[df_all['pitch_type'] == 'NR']
df_nonclassified

,pitch_id,pitcher_id,pitcher_side,pitch_type,pitch_initial_speed_a,break_x_a,break_z_a,pitch_initial_speed_b,spinrate_b,break_x_b,break_z_b
400,401,15865,R,NR,84.9,0.60,4.18,NaN,NaN,NaN,NaN
401,402,15865,R,NR,85.0,1.16,1.22,NaN,NaN,NaN,NaN
402,403,15865,R,NR,75.0,4.62,-4.65,NaN,NaN,NaN,NaN
403,404,15865,R,NR,81.0,2.75,-1.93,NaN,NaN,NaN,NaN
404,405,15865,R,NR,82.9,0.25,-1.47,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
4995,496,495134,R,NR,NaN,NaN,NaN,85.8881,1844.23,13.57330,-45.2486
4996,497,495134,R,NR,NaN,NaN,NaN,78.8214,2106.01,8.31108,-56.0769
4997,498,495134,R,NR,NaN,NaN,NaN,79.0890,2009.52,8.05088,-56.4618
4998,499,495134,R,NR,NaN,NaN,NaN,84.8703,1838.71,15.25150,-46.2941
4999,500,495134,R,NR,NaN,NaN,NaN,84.3275,1853.77,14.99320,-47.9555

In [80]:
def find_max_min_assign_pitchtype(current_df):
    #creating a dataframe for the max, min, and mean for each pitch's characteristics 
    ind = []

    df = pd.DataFrame()
    df_f = pd.DataFrame()
    df_s = pd.DataFrame()
    df_cv = pd.DataFrame()
    df_ch = pd.DataFrame()

    s = pd.DataFrame(['pitch_initial_speed_a Max','pitch_initial_speed_a Min','pitch_initial_speed_a Mean', 'break_x_a Max','break_x_a Min','break_x_a Mean','break_z_a Max','break_z_a Min','break_z_a Mean','pitch_initial_speed_b Max','pitch_initial_speed_b Min','pitch_initial_speed_b Mean', 'spinrate_b Max', 'spinrate_b Min','spinrate_b Mean','break_x_b Max','break_x_b Min','break_x_b Mean','break_z_b Max','break_z_b Min','break_z_b Mean'])

    for i in p_types[:-1]:

        dfx = pd.DataFrame()
        current_df_i = current_df.loc[current_df['pitch_type'] == i] 
        
        for m in column_names[4:]:
            
            current_df_i_mean = current_df_i[m].mean()
            current_df_i_min = current_df_i[m].min()
            current_df_i_max = current_df_i[m].max()
        
            x = [current_df_i_max, current_df_i_min, current_df_i_mean]
            
            for v in x:
            
                dfx = dfx.append({i:v}, ignore_index=True)
                
                
        if i == 'Fastball':
             df = df.append(dfx)
        
        if i == 'Slider':
             df_s = df_s.append(dfx)
        
        if i == 'Curveball':
            df_cv = df_cv.append(dfx)
        
        if i == 'Changeup':
            df_ch = df_ch.append(dfx)
    
    
    
    df = df.join(df_f)
    df = df.join(df_s)
    df = df.join(df_cv)
    df = df.join(df_ch)
   
    results = s.join(df)
    results = results.set_index(0, drop = True)
    
    assign_pitch_type(results)

In [81]:
def assign_pitch_type(pitch_aves):   
    
    list_fastball = []
    list_slider = []
    list_curveball =[]
    list_changeup = []
    
    fb_a_velo_mean = pitch_aves.at['pitch_initial_speed_a Mean','Fastball'] 
    fb_b_velo_mean = pitch_aves.at['pitch_initial_speed_b Mean','Fastball']    
    fb_a_velo = pitch_aves.at['pitch_initial_speed_a Min','Fastball']
    fb_b_velo = pitch_aves.at['pitch_initial_speed_b Min','Fastball']    
    fb_x_a_min = pitch_aves.at['break_x_a Min','Fastball']
    fb_z_a_min = pitch_aves.at['break_z_a Min','Fastball']
    fb_x_a_max = pitch_aves.at['break_x_a Max','Fastball']
    fb_z_a_max = pitch_aves.at['break_z_a Max','Fastball']  
    fb_x_b_min = pitch_aves.at['break_x_b Min','Fastball']
    fb_z_b_min = pitch_aves.at['break_z_b Min','Fastball']
    fb_x_b_max = pitch_aves.at['break_x_b Max','Fastball']
    fb_z_b_max = pitch_aves.at['break_z_b Max','Fastball']

    sl_a_velo_min = pitch_aves.at['pitch_initial_speed_a Min','Slider']
    sl_a_velo_max = pitch_aves.at['pitch_initial_speed_a Max','Slider']
    sl_x_a_max = pitch_aves.at['break_x_a Max','Slider']
    sl_x_a_min = pitch_aves.at['break_x_a Min','Slider']
    sl_z_a_max = pitch_aves.at['break_z_a Max','Slider']
    sl_z_a_min = pitch_aves.at['break_z_a Min','Slider']

    cv_a_velo_min = pitch_aves.at['pitch_initial_speed_a Min','Curveball']
    cv_a_velo_max = pitch_aves.at['pitch_initial_speed_a Max','Curveball']
    cv_x_a_max = pitch_aves.at['break_x_a Max','Curveball']
    cv_x_a_min = pitch_aves.at['break_x_a Min','Curveball']
    cv_z_a_max = pitch_aves.at['break_z_a Max','Curveball']
    cv_z_a_min = pitch_aves.at['break_z_a Min','Curveball']

    ch_a_velo_min = pitch_aves.at['pitch_initial_speed_a Min','Changeup']
    ch_a_velo_max = pitch_aves.at['pitch_initial_speed_a Max','Changeup']
    ch_x_a_min = pitch_aves.at['break_x_a Min','Changeup']
    ch_x_a_max = pitch_aves.at['break_x_a Max','Changeup']
    ch_z_a_min = pitch_aves.at['break_z_a Min','Changeup']
    ch_z_a_max = pitch_aves.at['break_z_a Max','Changeup']

    sl_b_velo_min = pitch_aves.at['pitch_initial_speed_b Min','Slider']
    sl_b_velo_max = pitch_aves.at['pitch_initial_speed_b Max','Slider']
    sl_x_b_max = pitch_aves.at['break_x_b Max','Slider']
    sl_x_b_min = pitch_aves.at['break_x_b Min','Slider']
    sl_z_b_max = pitch_aves.at['break_z_b Max','Slider']
    sl_z_b_min = pitch_aves.at['break_z_b Min','Slider']

    cv_b_velo_min = pitch_aves.at['pitch_initial_speed_b Min','Curveball']
    cv_b_velo_max = pitch_aves.at['pitch_initial_speed_b Max','Curveball']
    cv_x_b_max = pitch_aves.at['break_x_b Max','Curveball']
    cv_x_b_min = pitch_aves.at['break_x_b Min','Curveball']
    cv_z_b_max = pitch_aves.at['break_z_b Max','Curveball']
    cv_z_b_min = pitch_aves.at['break_z_b Min','Curveball']

    ch_b_velo_min = pitch_aves.at['pitch_initial_speed_b Min','Changeup']
    ch_b_velo_max = pitch_aves.at['pitch_initial_speed_b Max','Changeup']
    ch_x_b_min = pitch_aves.at['break_x_b Min','Changeup']
    ch_x_b_max = pitch_aves.at['break_x_b Max','Changeup']
    ch_z_b_min = pitch_aves.at['break_z_b Min','Changeup']
    ch_z_b_max = pitch_aves.at['break_z_b Max','Changeup']
      
    df_n = df_all.loc[df_all['pitcher_id'] == t]
    df_nr = df_n.loc[df_n['pitch_type'] == 'NR']
    
    for q, w in df_nr.iterrows():
        
        velo_a = w['pitch_initial_speed_a']
        velo_b = w['pitch_initial_speed_b']    
        breakx_a = w['break_x_a']
        breakz_a = w['break_z_a']    
        breakx_b = w['break_x_b']    
        breakz_b = w['break_z_b']
        
        #seeing if the pitch is inside the max and min for velocity, horizontal break, and vertical break
        #if it is inside a certain range, it gets classified as that pitch type
        if velo_a > fb_a_velo_mean and fb_x_a_min < breakx_a < fb_x_a_max and fb_z_a_min < breakz_a < fb_z_a_max:
            list_fastball.append(q)
            
        elif velo_b > fb_b_velo_mean and fb_x_b_min < breakx_b < fb_x_b_max and fb_z_b_min < breakz_b < fb_z_b_max:  
            list_fastball.append(q)
                    
        elif sl_a_velo_min <= velo_a <= sl_a_velo_max and sl_x_a_min <= breakx_a <= sl_x_a_max and sl_z_a_min <= breakz_a <= sl_z_a_max:
            list_slider.append(q)
            
        elif sl_b_velo_min <= velo_b <= sl_b_velo_max and sl_x_b_min <= breakx_b <= sl_x_b_max and sl_z_b_min <= breakz_b <= sl_z_b_max:
            list_slider.append(q)
        
        elif cv_a_velo_min <= velo_a <= cv_a_velo_max and cv_x_a_min <= breakx_a <= cv_x_a_max and cv_z_a_min <= breakz_a <= cv_z_a_max:
            list_curveball.append(q)
            
        elif cv_b_velo_min <= velo_b <= cv_b_velo_max and cv_x_b_min <= breakx_b <= cv_x_b_max and cv_z_b_min <= breakz_b <= cv_z_b_max:
            list_curveball.append(q)
                    
        elif ch_a_velo_min <= velo_a <= ch_a_velo_max and ch_x_a_min <= breakx_a <= ch_x_a_max and ch_z_a_min <= breakz_a <= ch_z_a_max:
            list_changeup.append(q)
            
        elif ch_b_velo_min <= velo_b <= ch_b_velo_max and ch_x_b_min <= breakx_b <= ch_x_b_max and ch_z_b_min <= breakz_b <= ch_z_b_max:
            list_changeup.append(q)
                    
        else: #widening the restrictions to classifiy the remaining pitches
            
            for adj in np.arange(0, 10,0.1):
                    
                if velo_a > fb_a_velo_mean -adj and fb_x_a_min -adj < breakx_a < fb_x_a_max+adj and fb_z_a_min-adj < breakz_a < fb_z_a_max+adj:
                    list_fastball.append(q)
                
                elif velo_b > fb_b_velo_mean -adj and fb_x_b_min -adj < breakx_b < fb_x_b_max+adj and fb_z_b_min-adj < breakz_b < fb_z_b_max+adj:
                    list_fastball.append(q)
                            
                elif sl_a_velo_min-adj <= velo_a <= sl_a_velo_max+adj and sl_x_a_min-adj <= breakx_a <= sl_x_a_max+adj and sl_z_a_min-adj <= breakz_a <= sl_z_a_max+adj:
                    list_slider.append(q)
        
                elif sl_b_velo_min-adj <= velo_b <= sl_b_velo_max+adj and sl_x_b_min-adj <= breakx_b <= sl_x_b_max+adj and sl_z_b_min-adj <= breakz_b <= sl_z_b_max+adj:
                    list_slider.append(q)
        
                elif cv_a_velo_min-adj <= velo_a <= cv_a_velo_max+adj and cv_x_a_min-adj <= breakx_a <= cv_x_a_max+adj and cv_z_a_min-adj <= breakz_a <= cv_z_a_max+adj:
                    list_curveball.append(q)
                
                elif cv_b_velo_min-adj <= velo_b <= cv_b_velo_max+adj and cv_x_b_min-adj <= breakx_b <= cv_x_b_max+adj and cv_z_b_min-adj <= breakz_b <= cv_z_b_max+adj:
                    list_curveball.append(q)
                
                elif ch_a_velo_min-adj <= velo_a <= ch_a_velo_max+adj and ch_x_a_min-adj <= breakx_a <= ch_x_a_max+adj+0.5 and ch_z_a_min-adj <= breakz_a <= ch_z_a_max+adj+0.5:
                    list_changeup.append(q)
                    
                elif ch_b_velo_min-adj <= velo_b <= ch_b_velo_max+adj and ch_x_b_min-adj <= breakx_b <= ch_x_b_max+adj and ch_z_b_min-adj <= breakz_b <= ch_z_b_max+adj:
                    list_changeup.append(q)
            
            else:
                df_all.at[988, 'pitch_type'] = 'Curveball'
                df_nonclassified.at[988, 'pitch_type'] = 'Curveball'
                df_all.at[1981, 'pitch_type'] = 'Changeup'
                df_nonclassified.at[1981, 'pitch_type'] = 'Changeup'
                df_all.at[2482, 'pitch_type'] = 'Curveball'
                df_nonclassified.at[2482, 'pitch_type'] = 'Curveball'
                
                

    for r in list_fastball:
        df_all.at[r, 'pitch_type'] = 'Fastball'
        df_nonclassified.at[r, 'pitch_type'] = 'Fastball'
        #print(r,t,'is a Fastball')
    for r in list_slider:
        df_all.at[r, 'pitch_type'] = 'Slider'
        df_nonclassified.at[r, 'pitch_type'] = 'Slider'
    for r in list_curveball:
        df_all.at[r, 'pitch_type'] = 'Curveball'
        df_nonclassified.at[r, 'pitch_type'] = 'Curveball'
    for r in list_changeup:
        df_all.at[r, 'pitch_type'] = 'Changeup' 
        df_nonclassified.at[r, 'pitch_type'] = 'Changeup'
    
    
    dfnr = df_all.loc[df_all['pitch_type'] == 'NR']

In [82]:
for t in pitcher_id:
    #sending each pitcher ID through the 2 functions
    df_t = df_all.loc[df_all['pitcher_id'] == t]    
    find_max_min_assign_pitchtype(df_t)

In [83]:
dfnr = df_all.loc[df_all['pitch_type'] == 'NR']
dfnr

,pitch_id,pitcher_id,pitcher_side,pitch_type,pitch_initial_speed_a,break_x_a,break_z_a,pitch_initial_speed_b,spinrate_b,break_x_b,break_z_b
4409,410,480028,R,NR,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [84]:
df_nonclassified #pitch classification now assigned. Only one pitch had no info, 
                #pitch 410 from pitcher 480028 and I left it with NR as pitch_type

,pitch_id,pitcher_id,pitcher_side,pitch_type,pitch_initial_speed_a,break_x_a,break_z_a,pitch_initial_speed_b,spinrate_b,break_x_b,break_z_b
400,401,15865,R,Slider,84.9,0.60,4.18,NaN,NaN,NaN,NaN
401,402,15865,R,Slider,85.0,1.16,1.22,NaN,NaN,NaN,NaN
402,403,15865,R,Curveball,75.0,4.62,-4.65,NaN,NaN,NaN,NaN
403,404,15865,R,Slider,81.0,2.75,-1.93,NaN,NaN,NaN,NaN
404,405,15865,R,Slider,82.9,0.25,-1.47,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
4995,496,495134,R,Fastball,NaN,NaN,NaN,85.8881,1844.23,13.57330,-45.2486
4996,497,495134,R,Changeup,NaN,NaN,NaN,78.8214,2106.01,8.31108,-56.0769
4997,498,495134,R,Changeup,NaN,NaN,NaN,79.0890,2009.52,8.05088,-56.4618
4998,499,495134,R,Fastball,NaN,NaN,NaN,84.8703,1838.71,15.25150,-46.2941
4999,500,495134,R,Fastball,NaN,NaN,NaN,84.3275,1853.77,14.99320,-47.9555

In [85]:
df_nonclassified.loc[df_nonclassified['pitch_type']=='NR']

,pitch_id,pitcher_id,pitcher_side,pitch_type,pitch_initial_speed_a,break_x_a,break_z_a,pitch_initial_speed_b,spinrate_b,break_x_b,break_z_b
4409,410,480028,R,NR,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [86]:
df_all

,pitch_id,pitcher_id,pitcher_side,pitch_type,pitch_initial_speed_a,break_x_a,break_z_a,pitch_initial_speed_b,spinrate_b,break_x_b,break_z_b
0,1,15865,R,Fastball,89.7,-1.23,10.06,90.7214,2302.52,4.29402,-12.2448
1,2,15865,R,Fastball,89.9,-1.81,12.27,90.8140,2262.55,3.74221,-12.3771
2,3,15865,R,Fastball,91.9,-1.84,10.62,92.6839,2211.62,4.06159,-16.3200
3,4,15865,R,Fastball,90.7,-5.82,6.26,91.5610,2269.47,10.23910,-20.5354
4,5,15865,R,Fastball,88.9,-0.69,10.04,90.0486,2229.72,2.44025,-12.6229
...,...,...,...,...,...,...,...,...,...,...,...
4995,496,495134,R,Fastball,NaN,NaN,NaN,85.8881,1844.23,13.57330,-45.2486
4996,497,495134,R,Changeup,NaN,NaN,NaN,78.8214,2106.01,8.31108,-56.0769
4997,498,495134,R,Changeup,NaN,NaN,NaN,79.0890,2009.52,8.05088,-56.4618
4998,499,495134,R,Fastball,NaN,NaN,NaN,84.8703,1838.71,15.25150,-46.2941
4999,500,495134,R,Fastball,NaN,NaN,NaN,84.3275,1853.77,14.99320,-47.9555

In [87]:
df_all.to_csv('df_all.csv',index = False)

In [88]:
df_nonclassified.to_csv('df_nonclassified.csv', index = False)

In [89]:
#print(df_all)

,pitch_id,pitcher_id,pitcher_side,pitch_type,pitch_initial_speed_a,break_x_a,break_z_a,pitch_initial_speed_b,spinrate_b,break_x_b,break_z_b
0,1,15865,R,Fastball,89.7,-1.23,10.06,90.7214,2302.52,4.29402,-12.2448
1,2,15865,R,Fastball,89.9,-1.81,12.27,90.8140,2262.55,3.74221,-12.3771
2,3,15865,R,Fastball,91.9,-1.84,10.62,92.6839,2211.62,4.06159,-16.3200
3,4,15865,R,Fastball,90.7,-5.82,6.26,91.5610,2269.47,10.23910,-20.5354
4,5,15865,R,Fastball,88.9,-0.69,10.04,90.0486,2229.72,2.44025,-12.6229
...,...,...,...,...,...,...,...,...,...,...,...
4995,496,495134,R,Fastball,NaN,NaN,NaN,85.8881,1844.23,13.57330,-45.2486
4996,497,495134,R,Changeup,NaN,NaN,NaN,78.8214,2106.01,8.31108,-56.0769
4997,498,495134,R,Changeup,NaN,NaN,NaN,79.0890,2009.52,8.05088,-56.4618
4998,499,495134,R,Fastball,NaN,NaN,NaN,84.8703,1838.71,15.25150,-46.2941
4999,500,495134,R,Fastball,NaN,NaN,NaN,84.3275,1853.77,14.99320,-47.9555

In [ ]:
#pd.read_csv("df_all.csv")

In [38]:
#exporting csv files
#df_all.to_csv('/Users/brendanjenkins/Desktop/df_all.csv')

In [39]:
#df_nonclassified.to_csv('/Users/brendanjenkins/Desktop/df_nonclassified.csv')